### ISSUE TITLE
Build website

### ISSUE THREAD

**Issue by drvinceknight** [PyDiff/PyDiff.github.io#4]

**Comment by drvinceknight** [comment]
@geraintpalmer work through http://jekyllrb.com/docs/home/, I can help.

**Comment by geraintpalmer** [comment]
Pushed a basic basic site branch start_jekyll_site
What do you think? Needs css stuff, looks exactly like [vknight.org](vknight.org) at the moment

**Comment by drvinceknight** [comment]
Go Head and push straight to master. We can view then easily (am on the run
most of today). Also mess with the css, play around with it :) No yellow
(jk).

**Comment by geraintpalmer** [comment]
Cool. If left in my hands it may well be yellow....
