### ISSUE TITLE
Lightning talk day: list yourself if you're up for giving a lightning talk

### ISSUE THREAD

**Issue by drvinceknight** [PyDiff/PyDiff.github.io#48]
Thinking of having a PyDiff session that would be entirely lightning talks. I suggest this issue is a list of potential lightning talk speakers. Once we've got a good number we'll schedule the lightning talk session.

- Vince (I can give one)

**Comment by martinjc** [comment]
- Martin (I can also give one ;-D)

I'll ask my curop students from this summer, they might like to talk too

**Comment by JamesGardiner** [comment]
- James (happy to give one)

Remind me how long these are? I'm thinking 5 minutes max, but just want to be sure...

**Comment by martinjc** [comment]
Yeah, generally 5 minutes max. Sometimes we're strict on that, sometimes we let people run over. I guess for this set of talks we'd be fairly strict on timing?

**Comment by JamesGardiner** [comment]
Does it depend on said people's propensity to buy you a pint afterwards?

**Comment by martinjc** [comment]
This is the exact reason I am not allowed to be in charge of the stopwatch

**Comment by drvinceknight** [comment]
> Sometimes we're strict on that, sometimes we let people run over. I guess for this set of talks we'd be fairly strict on timing?

I think for this session yeah: a strict 5 minutes, everyone starts clapping at 4 mins 50 seconds kind of thing :)

**Comment by encima** [comment]
Up for giving one.

**Comment by Huaraz2** [comment]
I can give one :smile:

**Comment by bennyrowland** [comment]
I am happy to give one.

**Comment by cromlyngames** [comment]
Happy to give one

**Comment by cromlyngames** [comment]
Drat Patrick barry

**Comment by drvinceknight** [comment]
Hi everyone here: planning on scheduling this lightning talk for the March meeting (21st).

**Comment by geraintpalmer** [comment]
I can do one.

**Comment by drvinceknight** [comment]
Closing this: will open another one for the next one :+1:
