### ISSUE TITLE
Book room for Oct 13th

### ISSUE THREAD

**Issue by drvinceknight** [PyDiff/PyDiff.github.io#6]
Should we say 1900? 

@geraintpalmer maybe book 1.02 (or whichever that one next to the 'UCAS' room is).

**Comment by geraintpalmer** [comment]
Booked 0.37 (maths support room) from 7:00pm - 9:00pm (although we could stay until building closes at 9:30).

**Comment by drvinceknight** [comment]
@evildmp just in case you read this and want to update the website: hole fire @geraintpalmer is going to find another room, this one doesn't have a projector (we spoke offline).

**Comment by geraintpalmer** [comment]
Now changed to 2.06, has a projector

**Comment by drvinceknight** [comment]
Merged in to site #11.
