### ISSUE TITLE
Lightning talks for April 17th

### ISSUE THREAD

**Issue by drvinceknight** [PyDiff/PyDiff.github.io#76]
On the 17th of April, the meetup will entirely be lightning talks (short 5 minute talks about anything of interest). Please comment here if you will be giving a lightning talk :)

**Comment by drvinceknight** [comment]
I have a lightning talk to give :) :+1:

**Comment by martinjc** [comment]
I do not yet have a lightning talk to give, but I am 99.99% sure I will have one by 7pm on the 17th April.

**Comment by Nikoleta-v3** [comment]
I would like to give a :zap: talk :hand:

**Comment by StephanieAngharad** [comment]
I would like to give a lightning talk :)

**Comment by alcarney** [comment]
I would like to give a lightning talk - just need to come up with one :)

**Comment by Huaraz2** [comment]
I can do one :smiling_imp: :+1:

**Comment by LordTandy** [comment]
I would like to give a talk. 👍

**Comment by steviebald** [comment]
Hi, I'd like to give a talk

**Comment by Heaford** [comment]
I have a talk to give :-)
